# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__)
np.show_config()


2.5.3
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.34.106.0  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy-release/numpy-release/.openblas
    version: 0.3.34.106.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-sp8l_b7i/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas 

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
a = np.random.random((2, 3, 5))


In [10]:
a = np.random.randint(0, 100, size=(2, 3, 5))


### 4. Print a.


In [9]:
a = np.random.random((2, 3, 5))
print(a)


[[[0.1858261  0.67155478 0.52610475 0.52789368 0.99850982]
  [0.68158375 0.41462466 0.36190151 0.56846901 0.62280581]
  [0.12099226 0.26608421 0.36036125 0.04931089 0.28545277]]

 [[0.11506668 0.27101215 0.75720083 0.23386351 0.70045992]
  [0.78392101 0.69452094 0.26716783 0.70372049 0.51124588]
  [0.50796416 0.42094131 0.38592686 0.8561328  0.97576243]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [13]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [14]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [15]:
print(a.size == b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [16]:
a + b


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [17]:
print (a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)


both arrays have the same size  but that doesnt mean same shape. so not competible for numpy broadcasting... answer for why not it is not possible to add a + b 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [19]:
c = b.transpose(1, 2, 0)

print(c)
print(c.shape)  # (2, 3, 5)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [20]:
d = a + c

print(d)
print(d.shape)  # (2, 3, 5)


[[[70. 29. 88. 72. 65.]
  [77. 59. 84. 20. 28.]
  [58. 18. 37. 28. 68.]]

 [[70. 27. 70. 29. 73.]
  [41. 31. 18. 27. 78.]
  [51. 48. 72. 60. 93.]]]
(2, 3, 5)


It works because a and c now has the same shape

In [21]:
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 2, 3)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [22]:

print("Array a:")
print(a)

print("\nArray d:")
print(d)


Array a:
[[[69 28 87 71 64]
  [76 58 83 19 27]
  [57 17 36 27 67]]

 [[69 26 69 28 72]
  [40 30 17 26 77]
  [50 47 71 59 92]]]

Array d:
[[[70. 29. 88. 72. 65.]
  [77. 59. 84. 20. 28.]
  [58. 18. 37. 28. 68.]]

 [[70. 27. 70. 29. 73.]
  [41. 31. 18. 27. 78.]
  [51. 48. 72. 60. 93.]]]


the relation ship is:


In [24]:
d = a + 1

In [25]:
d = a + c

In [31]:
print(d - a)

[[[69.55 28.55 87.55 71.55 64.55]
  [76.55 58.55 83.55 19.55 27.55]
  [57.55 17.55 36.55 27.55 67.55]]

 [[69.55 26.55 69.55 28.55 72.55]
  [40.55 30.55 17.55 26.55 77.55]
  [50.55 47.55 71.55 59.55 92.55]]]



### 12. Multiply a and c. Assign the result to e.


In [32]:
e = np.multiply(a, c)
print(e)

[[[0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]]

 [[0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]]]




### 13. Does e equal to a? Why or why not?


In [34]:

e = a * c
print(np.array_equal(e, a))


False




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Maximum value:", d_max)
print("Minimum value:", d_min)
print("Mean value:", d_mean)


Maximum value: 93.0
Minimum value: 18.0
Mean value: 52.96666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [36]:
f = np.empty((2, 3, 5))
print(f)
print(f.shape)


[[[0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]]

 [[0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]
  [0.45 0.45 0.45 0.45 0.45]]]
(2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
f = np.empty(d.shape)
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)
print(np.unique(f))

[[[ 75.  25.  75.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 75.   0.  25.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.   0.  25.  75.]
  [ 25.  25.  75.  75. 100.]]]
[  0.  25.  75. 100.]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [40]:
print("Array d:")
print(d)

print("\nArray f:")
print(f)

print("\nMinimum of d:", d_min)
print("Mean of d:", d_mean)
print("Maximum of d:", d_max)

print("\nUnique values in f:")
print(np.unique(f))


Array d:
[[[70. 29. 88. 72. 65.]
  [77. 59. 84. 20. 28.]
  [58. 18. 37. 28. 68.]]

 [[70. 27. 70. 29. 73.]
  [41. 31. 18. 27. 78.]
  [51. 48. 72. 60. 93.]]]

Array f:
[[[ 75.  25.  75.  75.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 75.   0.  25.  25.  75.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.   0.  25.  75.]
  [ 25.  25.  75.  75. 100.]]]

Minimum of d: 18.0
Mean of d: 52.96666666666667
Maximum of d: 93.0

Unique values in f:
[  0.  25.  75. 100.]


In [41]:
expected_f = np.select(
    [
        d == d_min,
        (d > d_min) & (d < d_mean),
        d == d_mean,
        (d > d_mean) & (d < d_max),
        d == d_max
    ],
    [0, 25, 50, 75, 100]
)

print("Is f correct?", np.array_equal(f, expected_f))

Is f correct? True


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [42]:

f_strings = np.empty(d.shape, dtype="<U1")

f_strings[d == d_min] = "A"
f_strings[(d > d_min) & (d < d_mean)] = "B"
f_strings[d == d_mean] = "C"
f_strings[(d > d_mean) & (d < d_max)] = "D"
f_strings[d == d_max] = "E"

print(f_strings)

[[['D' 'B' 'D' 'D' 'D']
  ['D' 'D' 'D' 'B' 'B']
  ['D' 'A' 'B' 'B' 'D']]

 [['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'A' 'B' 'D']
  ['B' 'B' 'D' 'D' 'E']]]
